### PR TITLE
SLING-11261 - Exception while starting CodehaleMetricsReporter compon…

### PR DESCRIPTION
**Pull request by sagarmiglani**
…ent on Windows Machine

### CODE REVIEW

**Comment by rombert** [comment]
LGTM. @mreutegg ?

**Review by mreutegg — APPROVED** [review]
+1

**Comment by sagarmiglani** [comment]
Thanks @rombert and @mreutegg for the review. Can we merge and release?

**Comment by rombert** [comment]
Thanks for the contribution @sagarmiglani

**Pull request merged**
