### PR TITLE
SLING-9382 Shutdown executor before closing db connection SLING-9381 Upgrade RRD4J to version 3.6 (Java 11 compatible)

### PR DESCRIPTION
**Pull request by harshmehta5**

### CODE REVIEW

**Comment by mreutegg** [comment]
Looks good to me.

**Comment by rombert** [comment]
Thanks for the PR @harshmehta5 . Can you please also create a jira issue (maybe 2, one for each fix?) and reference them in the commit titles?

E.g. 
`SLING-1234 : Upgrade RRD4J to version 3.6 (Java 11 compatible)`
`SLING-2345: Shutdown executor before closing db connection`

**Comment by rombert** [comment]
SonarCloud failed but I don't think there are any code issues with the PR. So from my POV it's good to merge as soon as we have the Jira issues.

**Comment by harshmehta5** [comment]
Created issue SLING-9381

**Comment by rombert** [comment]
Thank you @harshmehta5 . Could I ask you to change the commit titles as well? You probably want to use something like `git rebase -i origin/master` and edit the titles to reference the Jira issues. Finally, please use `git push -f` so that we don't create unnecessary commits.

**Comment by rombert** [comment]
Perfect, thanks a lot for seeing this through @harshmehta5

**Pull request merged**
